{% set name = "oauthlib" %}
{% set version = "2.0.6" %}
{% set compress_type = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "ce57b501e906ff4f614e71c36a3ab9eacbb96d35c24d1970d2539bbc3ec70ce1" %}
{% set build = 0 %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - cryptography
    - pyjwt >=1.0.0
    - blinker

test:
  imports:
    - oauthlib
    - oauthlib.oauth1
    - oauthlib.oauth1.rfc5849
    - oauthlib.oauth1.rfc5849.endpoints
    - oauthlib.oauth2
    - oauthlib.oauth2.rfc6749
    - oauthlib.oauth2.rfc6749.clients
    - oauthlib.oauth2.rfc6749.endpoints
    - oauthlib.oauth2.rfc6749.grant_types

about:
  home: https://github.com/idan/oauthlib
  license_file: LICENSE
  license: BSD 3-Clause
  license_family: BSD
  summary: 'A generic, spec-compliant, thorough implementation of the OAuth request-signing logic'
  dev_url: https://github.com/idan/oauthlib
  doc_url: https://oauthlib.readthedocs.io

extra:
  recipe-maintainers:
    - pmlandwehr
