travis:
  secure:
    BINSTAR_TOKEN: ak8EGJpSULk792wXRxEDVWF2LkAehBQkeolHRdAuJ2qdixxHsnqgqDEUEcsoaAJ4eF0UA9fo/YPgNnCp9qHe19AaLoiRCDs6Cg9ItedocHw+5GQqw6p2+OudJptlKV0TXi6qfUg3AiKm50QX3gMGQA0cPE3gkE4zj3vVEUPsDjFlyDIWZS59dbSdkUajDnKZ82OZ0ne+npSzs2rJdNulowRBiI+vFVWVJ+Kupv0eolqeCSd02Xz1Bxt3Ye4pgniYaAP/boDZUni0Hce1X4pj3NXsvcDQLviCHSrP9mNKwji46Wizc6kX9/XNSZAdDtuOzjJsgp3qIErnEPlRu1+7jqjLy1Zt6F2OFU5dT44bB6lmQCgOxBEWqLWweDx3VYw+ge0EmpOME7Muj3+l5TkcgjYPb4GVzPym7/VvmhaiRRLDe46+fOvKIIVwPlzcrMz8f5RRwDaUTjnXI/AyM96ILTQQgNf7EfCSmXw4tsLZhW+f/XtQ5PQzI5T1BNcVgdbN6YD4q+MPJ89eZA252ojT/LqxlnbT7tsdKC6e/2fC8ZuRLgoZOVEKC9QiaQQq8rJmlHByAn2rCE1e5MitZOrjMw7CK5CMkTv8PwXuSLIhEIrlBMQtjrhVd1X6jYJbCw143d7tYMjy0pmoxGVfGOwDo7ZIvciM02/vOJAZNpxWBvo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
