travis:
  secure:
    BINSTAR_TOKEN: XOyVIGltxbJToxaauqsKobbtKEK4RH7uRAvLt7D0djbxkmaS1e6e0TeTmnVrqih7oPVA75/DU9w9srFXUSyEH00YfKOgZDl27HO7bn35UZPS+/MTkvMXcdizLVR5VEm1BaXKYuV1Xug5V66b8YealLvhTbXeokekGRcC21kDW6956w2ef08gIxdLnh6z2T6KQkj9Zs4R7LGKjxzy4lDYMjGX0VZ1or1v0qXamwSqoAQGLX7LiSyrO9RHEs28P9GDFVrxggkRhqLuzPWfTIWbKvK2FZS3lYQuzUL8Js2LHNsxKCpUvg4FlgwdVGeCVC/F3pjtwBbYh0CgfTy0lxbYbSjpCj+4dFx2blZNd5wlIuUaoW7ZFvPhC7SQ4sLsHDQeDYE7q4G1yW0Alv/6ONop1pDn23c4GcSrWtdwAgH/E9rNwjQUIw7APzVjw3f5OoxerBUqzOMd1IdMDD5oIXM23VQNRy/iE6nI1Wjqn8lxObSjEy64z3BVnvd/yXMIXaHJAKYdYtiBvLz03jueb4k2G9sbwQuuCqOHbaOnuG5bJKn2tA6tQoclRlgAA5/RF8Y9GdIrvTCw1T20gzP79XHID+hQo3dp6cfWk11TxcDdQkp5RorBH0gKmACrdqpas8NKemox8hSAFHmlU5Fy/tRpsqEwOFRQFTLQaJmSo9YcssI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
