travis:
  secure:
    BINSTAR_TOKEN: RUmsKvqfvjdOi3dzghpCsJnBp8IpRzsG4w1Evj5u24CmHh2UmYdPcG36TFdB840ttm0ovy7/JM7qCx+yl1x6LEilLozMF1ionnDbwV1QGmoSVLAtLzsLe7xiTI4B71D3fBWVRTvTtulcMu2uosxqaeDYLKc8xwLEp8Bj7fLh4fb8RaMLrnX4oCjmmXAV6BzIPO0aA0emzusAJjEfWKTxr+VBNLHgFQoScOyF9RhiWCJpEO6fbN3QkB8+D8nhej8zfOyNGrDxNnLsEF6O/aBqoVbzzvlZJWsTgdhUqeX0r1y0ahdfumU9mBwspPJeHvgs2pLZ9Zyx1XyiMdcNZ3CEAPlEGpnygiFGtuua5ubi9iHbGqAM+0PrweLPmupoms1YbKsgZ+zjLrXf+3gghDsZ5qFrVWebbXoVbeUjVNtpPUBCPk7vxfnoj3NOpLNESuv2igaG96CXB6VfrGl408HdqHbMGsanxEHUIIcnSJ5zdWrxGlat4Yp6ly+6a52ZHi+BNl3tih5vjiC+mNuFETo7CZFCcJsvWOJat48Tu3lxLHXcLksSRoB5xK7+thx3gMJB3W/e7i9RTtePh7Y9oEc/lgNuTtE8NaSdu0yaMHUt6+1WIRkfHTwOkrTgSYlc2GRhsMJisk55h5R9X1LpFY7yqm+cXm4zdh1NUcvrCZcZXtU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
